### ISSUE TITLE
AngularJs - Javascript editor does not open completion for angular model.

### ISSUE THREAD

**Issue by Archana14** [angelozerr/angularjs-eclipse#146]
I have done AngularJs eclipse setup as per this tutorial.
But in JavaScript editor, it does not open completion for angular model.
In fact when enter dot(.) it doesn't show anything at all. I tried to trouble shoot as well as per tutorial. 
I don't see any errors in error logs and console also shows all the tern related commands.

Thank you in advance

**Comment by angelozerr** [comment]
I'm sorry but with your info, I cannot help you more.

Which version of AngularJS Eclipse have you installed?

Could you share please your project (ex : create a project in your github).

**Comment by Archana14** [comment]
Hi,
I am using AngularJS Eclipse 0.8.0.
I am using phonecat-app from https://github.com/angular/angular-phonecat
I just imported phonecat-app in my eclipse worskspace and trying to so setup using this https://github.com/angelozerr/angularjs-eclipse/wiki/Getting-Started

**Comment by angelozerr** [comment]
AngularJS Eclipse is not perfect and there is some cases that I have not managed, but if you don't tell me exactly which completion which causes problem (a screenshot for instance are welcome)  inside which HTML or JS file, I cannot help you.

**Comment by Archana14** [comment]
When I typed phonecatApp. , auto completion does not come up. It is inside JS file.

Here is the screen shot
![image](https://cloud.githubusercontent.com/assets/11054870/6538585/15041a0e-c432-11e4-9bec-8396afe0c284.png)

**Comment by Archana14** [comment]
It is particularly, JavaScript editor function I am trying from the tutorial. Below is the screenshot from tutorial...
![image](https://cloud.githubusercontent.com/assets/11054870/6538624/a2820bde-c432-11e4-905a-362b63e0cea0.png)

**Comment by vrubezhny** [comment]
Yeah, we've also faced this issue... :(
Not working CA is not that. Look at the right-bottom corner of Eclipse's screenshot - there's a builder working. It's almost never finishing its job - actually it's a validation job.
That's because Archana14 did 'npm install' on the project. And this command has added 'node_modules' directory which contains abour 1200 javascript files - let's say not a small count (and size as well).
We've tried to exclude that folder by modifying JSDT's 'Include Path' project preference, but unfortunately it didn't help.

Angelo, where in Tern.java's code I can see a place where you're making a decision on what scripts have to be uploaded to/synchronized with the server? (I mean that Tern.java - JSDT Include Path relation). 

Thanks in advance.

**Comment by Archana14** [comment]
Yes that the validation job. Thats fine because I actually tried to do html syntax validation in prefrences and then it tried to validate the project and that is showing some errors on node-modules. But thats ok. If I don't validate I wont get any error on node-modules. My only aim is to get auto completion as mentioned in my last screenshots. Thank you

**Comment by vrubezhny** [comment]
All I can suggest at the moment is to try to exclude node_modules/, scripts/ and test/ folders from JSDT Include Path Open Project Properties -> JavaScript -> Include Path Property Page and add those folders to the 'Excluded' list. 

See, how I've done it:

![Include Path property](http://jeremy.ru/jeremy/IncludePath.png)

**Comment by alexeykazakov** [comment]
Endless or a very long validation job is a big problem actually. Because it locks your workspace.

**Comment by angelozerr** [comment]
> That's because Archana14 did 'npm install' on the project. And this command has added 'node_modules' directory which contains abour 1200 javascript files

Thanks @vrubezhny for your clarification! Ok this issue is about tern performance. But the thing I don't understand is that if @Archana14 uses 0.8.0, it doesn't benefit with async tern completion  https://github.com/angelozerr/tern.java/wiki/New-and-Noteworthy-0.9.0#async-tern-completion so her eclipse should freeze when completion is executed. @Archana14  is your eclipse freeze when completion opens?

>We've tried to exclude that folder by modifying JSDT's 'Include Path' project preference, but unfortunately it didn't help.

Yes it's normal, because as I said you @vrubezhny tern script path must be improved and it must support exclude path https://github.com/angelozerr/tern.java/issues/150

I'm very busy with the 0.9.0 and I would like to provide:

 * Extensible Validator https://github.com/angelozerr/tern.java/wiki/Tern-Linter based on JSHint, ESLInt, etc 
 * JSON Editor https://github.com/angelozerr/eclipse-wtp-json

So I have no time for the moment to improve tern script path.

>Angelo, where in Tern.java's code I can see a place where you're making a decision on what scripts have to be uploaded to/synchronized with the server? (I mean that Tern.java - JSDT Include Path relation).

If you wish to support JSDT exclude path, we must : 

 * support exclude tern script path (it should be cool too to add exclude path with UI)
 * update JTern.java - JSDT Include Path relation https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.jsdt/src/tern/eclipse/ide/jsdt/internal/JSDTClassPathManager.java#L219

But my idea is to support complex tern script path with pattern exclusion/inclusion like JSHint-Eclipse have started to done https://github.com/eclipsesource/jshint-eclipse/blob/master/bundles/com.eclipsesource.jshint.ui/src/com/eclipsesource/jshint/ui/internal/preferences/PathPattern.java

I would like to have a powerful tern script path to support for instance exclude path from bower.json or files like https://github.com/jquery/jquery/blob/master/.jshintignore.

@vrubezhny  It's a big task, but if you can help me it should be very fantastic. If you wish I could create an issue with my idea that I have described you here.

**Comment by vrubezhny** [comment]
@Archana14 I'd suggest you to use Tern.java/AngularJS-Eclipse v.0.8.2 - it shouldn't be locked on big projects + exclude extra directories from the build (as I shown above).

@angelozerr JSDT's Include Path contains the possibility to include/exclude different directories and single files and to use wildcards in names for inclusion and exclusion patterns. 
Another point is that Tern/Angular features (including the validation should work with the same inclusion/exclusion patterns as JSDT does. In case you're including/excluding some path for Tern but not for JSDT - they could behave unexpectedly.
Thanks for the pointers in the Tern's core. I'll look on how it works now,

**Comment by angelozerr** [comment]
> @Archana14 I'd suggest you to use Tern.java/AngularJS-Eclipse v.0.8.2

Or install 0.9.0 SNAPSHOT if you wish to start beneit with JSHInt validation but it's not finished!

> @angelozerr JSDT's Include Path contains the possibility to include/exclude different directories and single files and to use wildcards in names for inclusion and exclusion patterns. 

Yes I have seen that. I would like to support that with tern script path too and if we can manage together https://github.com/jquery/jquery/blob/master/.jshintignore.it should be very cool too.

> Another point is that Tern/Angular features (including the validation should work with the same inclusion/exclusion patterns as JSDT does. In case you're including/excluding some path for Tern but not for JSDT - they could behave unexpectedly.

Totally agreed with you. My idea is to improve https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.jsdt/src/tern/eclipse/ide/jsdt/internal/JSDTClassPathManager.java#L219 to synch JSDT inclusion/exclusion path with Tern script path inclusion/exclusion path. As I said you I would like to avoid having JSDT dependencies in Tern, that's why I prefer synchronize JSDT & Tern path.

**Comment by Archana14** [comment]
Thank you so much everyone for helping me.
I am using AngularJS-Eclipse v.0.8.2 now. and got fresh phonecat app project from github.Imported in my eclipse and didn't do validation step(properties->validation->html syntax) that I mentioned before and now u wont see any node_modules error. And the auto completion is also available now.
Thanks again
![image](https://cloud.githubusercontent.com/assets/11054870/6542323/fb17d860-c4c2-11e4-809c-9d3f5a68855c.png)

**Comment by angelozerr** [comment]
@vrubezhny pay attention. I have splitted Tern JSDT to 2 Core and UI plugins. So JSDT Class Path Manager are hoste now at https://github.com/angelozerr/tern.java/blob/master/eclipse/jsdt/tern.eclipse.ide.jsdt.core/src/tern/eclipse/ide/jsdt/internal/core/JSDTClassPathManager.java
