### ISSUE TITLE
Is it possible to use this without changing the project type?

### ISSUE THREAD

**Issue by andrewducker** [angelozerr/angularjs-eclipse#147]
I'm using a Google App Engine project, and I can't change the project type (it's a mixture of Java and JS).

If I could add an Angular Facet to this, that would be fantastic.  But that doesn't seem to be an option.

Is it possible to do this without changing the project type?

Thanks!

**Comment by angelozerr** [comment]
Since 0.8.0, tern.java and AngularJS Eclipse doesn't use Eclipse nature. In other words your project :

 * has tern nature if your project contains .tern-project
 * has angular nature if .tern-project contains angular plugin.

The Convert action does that.

> Is it possible to do this without changing the project type?

If project type is the same thing than Eclipse nature, yes it's possible.

**Comment by angelozerr** [comment]
None answer, I close this issue.
