### ISSUE TITLE
No code suggestions

### ISSUE THREAD

**Issue by TeodorKolev** [angelozerr/angularjs-eclipse#156]
No code suggestions, neither in html, neither in js files

**Comment by angelozerr** [comment]
I cannot help you more with your info

**Comment by TeodorKolev** [comment]
I create function in .js and when I add ng-click it did not show it. ng-class did not work also. I don't mention that some functions like ng-if is totally unfamiliar to this plugi

**Comment by jabby** [comment]
DId you activate the plugin on your project ? I use this plugin since last september and ng-if was always activated for angular-js project. If you want to verify the activation of the plugin check in your project folder. You should see a .tern-project file.

If you open this file, you should see something like : 

> {"ide":{},"plugins":{"guess-types":{},"jasmine":{},"angular":{},"protractor":{}},"libs":["ecma5","browser"]}

**Comment by TeodorKolev** [comment]
Yes, I have it, and there is no relation to html js and css

**Comment by angelozerr** [comment]
Perhaps its a problem with config of tern script path.

Its very hard to help you with your info. Is angular. // here ctrl space must show module bind

Is working?

Please give us a real sample which doesnt work like sharing your project

**Comment by angelozerr** [comment]
@TeodorKolev please share your project which doesn't work and which completion you are expecting.

**Comment by angelozerr** [comment]
None answer, I close this issue.
