### ISSUE TITLE
Debug as > Error while debug as protractor

### ISSUE THREAD

**Issue by Saurabh06** [angelozerr/angularjs-eclipse#208]
I have installed webclipse and node eclipse javscript debugger fro debugging protractor script i am getting below error 
![image](https://cloud.githubusercontent.com/assets/17181080/17479310/7ffba88e-5d8f-11e6-8b30-cce0e6779b1d.png)
May i know why this error i am getting while debugging in eclipse neon having webclipse and nodeclipse javscript debugger is installed , but i am able to run without any problem

**Comment by angelozerr** [comment]
Which tern debugger do use (Webclipse, Nodeclipse, JSDT)? (see https://github.com/angelozerr/angularjs-eclipse/wiki/Protractor#debug

**Comment by piotrtomiak** [comment]
@Saurabh06 - if you are using Webclipse, you should select and use it's JavaScript debugger instead of Nodeclipse one. From all 3 of the Chromium Dev Tools based debuggers - Webclipse, Nodeclipse, Neon JSDT - Webclipse is providing you the best experience. Note, that Webclipse has forked Chromium Dev Tools plugins and they are incompatible with Nodeclipse, so having both installed breaks Nodeclipse JavaScript debugger.

**Comment by Saurabh06** [comment]
thanks @piotrtomiak, its working now..
